Repository pactus-project/pactus-gui, pull requests merged in 2025-04, with the labels that each got.

#159 feat: implement dashboard section from `Dashboard` screen
  lib/src/core/extensions/context_extensions.dart
  lib/src/features/confirmation_seed/presentation/sections/confirmation_seed_words_grid_section.dart
  lib/src/features/generation_seed/presentation/sections/seeds_words_grid_section.dart
  lib/src/features/restoration_seed/presentation/sections/restoration_seed_words_grid_section.dart
Labels: feature

#165 feat(core): implement multi-network mode for development and testing
  .gitignore
  CHANGELOG.md
  analysis_options.yaml
  lib/app.dart
  lib/main.dart
  lib/src/core/common/widgets/keyboard_shortcut_widget.dart
  lib/src/core/constants/cli_constants.dart
  lib/src/core/di/locator.dart
  lib/src/core/enums/app_enums.dart
  lib/src/core/enums/app_environment.dart
  lib/src/core/extensions/context_extensions.dart
  lib/src/core/router/app_router.dart
  lib/src/core/router/route_name.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_manager_bloc.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_manager_event.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_manager_state.dart
  lib/src/core/utils/window_manager.dart
  lib/src/data/models/app_config/app_config.dart
  lib/src/data/models/app_config/localnet_config.dart
  lib/src/data/models/app_config/mainnet_config.dart
  lib/src/data/models/app_config/testnet_config.dart
  lib/src/features/dev_mode/core/utils/create_node_dialog.dart
  lib/src/features/dev_mode/data/repositories/environment_repository.dart
  lib/src/features/dev_mode/presentation/bloc/directory_check_bloc.dart
  lib/src/features/dev_mode/presentation/bloc/directory_check_event.dart
  lib/src/features/dev_mode/presentation/bloc/directory_check_state.dart
  lib/src/features/dev_mode/presentation/bloc/environment_selection_cubit.dart
  lib/src/features/dev_mode/presentation/bloc/environment_selection_state.dart
  lib/src/features/dev_mode/presentation/screens/dev_mode_screen.dart
  lib/src/features/dev_mode/presentation/widgets/dialog_action_widget.dart
  lib/src/features/dev_mode/presentation/widgets/dialog_content_widget.dart
  lib/src/features/dev_mode/presentation/widgets/dialog_title_widget.dart
  lib/src/features/dev_mode/presentation/widgets/directory_checker_bloc_widget.dart
  lib/src/features/dev_mode/presentation/widgets/environment_radio_option.dart
  lib/src/features/dev_mode/presentation/widgets/environment_selector.dart
  lib/src/features/dev_mode/presentation/widgets/generate_seed_and_set_password_section.dart
  lib/src/features/dev_mode/presentation/widgets/generate_seeds_widget.dart
  lib/src/features/dev_mode/presentation/widgets/header_title_widget.dart
  lib/src/features/dev_mode/presentation/widgets/set_password_widget.dart
  lib/src/features/dev_mode/presentation/widgets/submit_button_widget.dart
  lib/src/features/finish/presentation/screen/finish_screen.dart
  lib/src/features/initializing/presentation/screen/initializing_screen.dart
  lib/src/features/master_password/presentation/screen/master_password_screen.dart
  lib/src/features/password/presentation/screen/unlock_password_screen.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  lib/src/features/validator_config/core/utils/methods/is_not_empty_directory_method.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#168 refactor: align form accessibility & theming with figma specs
  CHANGELOG.md
  lib/src/core/common/sections/navigation_footer_section.dart
  lib/src/core/common/widgets/standard_page_layout.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/master_password/presentation/sections/master_password_section.dart
  lib/src/features/restoration_seed/presentation/screen/restoration_seed_screen.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#169 feat: persistent storage for theme and localization
  CHANGELOG.md
  lib/src/core/constants/storage_keys.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/main/language/presentation/bloc/language_bloc.dart
  lib/src/features/main/language/presentation/bloc/language_state.dart
  lib/src/features/main/theme/bloc/theme_bloc.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  pubspec.lock
  pubspec.yaml
  test/src/core/common/widgets/theme_switcher_test.dart
  test/src/features/main/language/language_bloc_test.dart
  test/src/features/main/language/language_state_test.dart
  test/src/features/main/language/presentation/bloc/language_bloc_test.dart
  test/src/features/main/theme/bloc/theme_bloc_test.dart
Labels: feature

#176 feat(faq): implementation `faq` section
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/dashboard/presentation/screen/dashboard_screen.dart
  lib/src/features/faq/presentation/sections/faq_section.dart
  lib/src/features/faq/presentation/widgets/faq_item.dart
  pubspec.lock
Labels: feature

#180 Fix/support theming and eliminate hardcoded color definitions
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/src/core/common/widgets/screen_header_widget.dart
  lib/src/core/constants/feature_flag.dart
  lib/src/core/extensions/string_extensions.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_cubit.dart
  lib/src/core/utils/daemon_manager/node_config_data.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/dashboard/presentation/screen/dashboard_screen.dart
  lib/src/features/dashboard/presentation/widgets/pane_items.dart
  lib/src/features/dashboard/presentation/widgets/title_pane_item.dart
  lib/src/features/faq/presentation/screen/faq_screen.dart
  lib/src/features/faq/presentation/sections/faq_section.dart
  lib/src/features/finish/presentation/screen/finish_screen.dart
  lib/src/features/generation_seed/presentation/sections/seed_notes_section.dart
  lib/src/features/generation_seed/presentation/widgets/copy_to_clip_board_button.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/initialize_mode/presentation/widgets/radio_button_group_widget.dart
  lib/src/features/initializing/presentation/screen/initializing_screen.dart
  lib/src/features/main/language/presentation/widget/language_combo_box.dart
  lib/src/features/password/presentation/screen/unlock_password_screen.dart
  lib/src/features/restoration_seed/presentation/screen/restoration_seed_screen.dart
  lib/src/features/settings/presentation/screens/settings_screen.dart
  lib/src/features/settings/presentation/sections/settings_section.dart
  lib/src/features/validator_config/core/utils/methods/show_fluent_alert_method.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  pubspec.yaml
Labels: refactor

#182 Refactor/extract all hardcoded strings and add localization support
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/dashboard/core/enums/dashboard_card_type.dart
  lib/src/features/dashboard/presentation/widgets/addresses_card_header.dart
  lib/src/features/dashboard/presentation/widgets/dashboard_card_widget.dart
  lib/src/features/dev_mode/core/utils/create_node_dialog.dart
  lib/src/features/dev_mode/presentation/widgets/dialog_action_widget.dart
  lib/src/features/dev_mode/presentation/widgets/directory_checker_bloc_widget.dart
  lib/src/features/dev_mode/presentation/widgets/environment_radio_option.dart
  lib/src/features/dev_mode/presentation/widgets/generate_seed_and_set_password_section.dart
  lib/src/features/dev_mode/presentation/widgets/submit_button_widget.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/validator_config/core/utils/methods/show_fluent_alert_method.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor

#186 Refactor/disable some dashboard feature
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/about_us/presentation/widgets/about_item_sub_list.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/node_logs/presentation/screens/node_logs_screen.dart
  lib/src/features/transactions/presentation/screens/transactions_screen.dart
  lib/src/features/wallet/presentation/screens/wallet_screen.dart
  pubspec.yaml
Labels: refactor

#196 update: adjustment background color of seed input component
  CHANGELOG.md
  lib/src/features/confirmation_seed/presentation/sections/confirmation_seed_words_grid_section.dart
  lib/src/features/generation_seed/presentation/sections/seeds_words_grid_section.dart
  lib/src/features/restoration_seed/presentation/sections/restoration_seed_words_grid_section.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature

#197 fix(dashboard): update dashboard item color according figma specs
  CHANGELOG.md
  assets/icons/ic_dashboard.svg
  lib/src/features/dashboard/presentation/screen/dashboard_screen.dart
  lib/src/features/dashboard/presentation/widgets/icon_pane_item.dart
  pubspec.lock
Labels: refactor

#198 refactor: fix UI issues in dashboard feature
  CHANGELOG.md
  lib/src/core/common/widgets/app_bar_button.dart
  lib/src/core/common/widgets/customized_appbar.dart
  lib/src/features/dashboard/presentation/screen/dashboard_home_screen.dart
  pubspec.yaml
Labels: refactor
