Repository pactus-project/pactus-gui, pull requests merged in 2025-03, with the labels that each got.

#115 fix(splash:unlockPassword): refactor some cli commands settings
  CHANGELOG.md
  lib/main.dart
  lib/src/core/di/locator.dart
  lib/src/core/enums/app_os_separator.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_cubit.dart
  lib/src/core/utils/storage_utils.dart
  lib/src/features/password/presentation/screen/unlock_password_screen.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  pubspec.yaml
Labels: feature

#120 feat: implement feature of `accentColor` to GUI app
  CHANGELOG.md
  lib/main.dart
  lib/src/core/common/cubits/app_accent_color_cubit.dart
  lib/src/core/common/sections/navigation_footer_section.dart
  lib/src/core/common/widgets/accent_color_picker_widget.dart
  lib/src/core/common/widgets/custom_input_widget.dart
  lib/src/core/common/widgets/custom_radio_button.dart
  lib/src/core/common/widgets/theme_switcher.dart
  lib/src/features/finish/presentation/screen/finish_screen.dart
  lib/src/features/generation_seed/presentation/widgets/copy_to_clip_board_button.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/initializing/presentation/screen/initializing_screen.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  pubspec.yaml
  test/src/core/common/widgets/theme_switcher_test.dart
Labels: feature

#119 fix: Resolve initialization bug in remote node connection step
  CHANGELOG.md
  lib/src/features/initializing/presentation/screen/initializing_screen.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  pubspec.yaml
Labels: bug

#125 feat: optimize and align `accent color` with `Widgetbook` repository
  CHANGELOG.md
  lib/main.dart
  lib/src/core/common/cubits/app_accent_color_cubit.dart
  lib/src/core/common/sections/navigation_footer_section.dart
  lib/src/core/common/widgets/accent_color_picker_widget.dart
  lib/src/core/common/widgets/custom_input_widget.dart
  lib/src/core/common/widgets/custom_radio_button.dart
  lib/src/core/constants/cli_constants.dart
  lib/src/core/constants/storage_keys.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_cubit.dart
  lib/src/core/utils/storage_utils.dart
  lib/src/features/finish/presentation/screen/finish_screen.dart
  lib/src/features/generation_seed/presentation/widgets/copy_to_clip_board_button.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/initializing/presentation/screen/initializing_screen.dart
  lib/src/features/password/presentation/screen/unlock_password_screen.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  pubspec.yaml
  test/src/core/utils/storage_utils.dart
Labels: feature

#129 refactor: optimize navigation of dashboard route and welcome
  CHANGELOG.md
  lib/src/core/router/basic_routes.dart
  lib/src/features/dashboard/presentation/screen/dashboard_screen.dart
  lib/src/features/finish/presentation/screen/finish_screen.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/password/presentation/screen/unlock_password_screen.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  pubspec.yaml
Labels: enhancement

#135 feat: Implement Custom Window Header for Desktop Platforms
  .github/workflows/ci.yml
  CHANGELOG.md
  assets/icons/ic_close.svg
  assets/icons/ic_maximize.svg
  assets/icons/ic_minimize.svg
  lib/main.dart
  lib/src/core/common/navigation_pans/create_local_node_pane.dart
  lib/src/core/common/navigation_pans/remote_node_pane.dart
  lib/src/core/common/navigation_pans/restoring_node_pane.dart
  lib/src/core/common/widgets/app_bar_button.dart
  lib/src/core/common/widgets/app_layout.dart
  lib/src/core/common/widgets/customized_appbar.dart
  lib/src/core/common/widgets/theme_switcher.dart
  lib/src/core/utils/gen/assets/assets.gen.dart
  lib/src/data/data_sources/remote_data_state.dart
  lib/src/data/data_sources/remote_data_state.freezed.dart
  lib/src/features/blockchain_get_info/presentation/pages/blockchain_info_section.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/password/presentation/screen/unlock_password_screen.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
  test/src/core/common/widgets/theme_switcher_test.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature

#139 feat: implement custom dashboard header
  CHANGELOG.md
  assets/icons/ic_clock.svg
  assets/icons/ic_code.svg
  assets/icons/ic_connection.svg
  assets/icons/ic_reachbility.svg
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/src/core/common/widgets/app_bar_button.dart
  lib/src/core/common/widgets/app_layout.dart
  lib/src/core/common/widgets/customized_appbar.dart
  lib/src/core/common/widgets/icon_action_button.dart
  lib/src/core/utils/gen/assets/assets.gen.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/dashboard/presentation/screen/dashboard_screen.dart
  pubspec.yaml
Labels: feature

#137 ci: modularize CI/CD pipeline by splitting actions into reusable files
  .github/actions/code-quality/check-dart-format/action.yml
  .github/actions/code-quality/generate-assets/action.yml
  .github/actions/code-quality/generate-locale-files/action.yml
  .github/actions/code-quality/validate-assets/action.yml
  .github/actions/code-quality/validate-localization/action.yml
  .github/actions/linux/add-daemon-files/action.yml
  .github/actions/linux/build-artifacts-amd64/action.yml
  .github/actions/linux/build-artifacts-arm64/action.yml
  .github/actions/linux/install-dependencies-amd64/action.yml
  .github/actions/linux/release/action.yml
  .github/actions/macos/build-artifacts/action.yml
  .github/actions/macos/install-dependencies/action.yml
  .github/actions/macos/release/action.yml
  .github/actions/utils/debugging-logger/action.yml
  .github/actions/utils/extract-tag-metadata/action.yml
  .github/actions/utils/generate-download-links/action.yml
  .github/actions/utils/install-flutter-dependencies/action.yml
  .github/actions/utils/move-files-to-artifacts/action.yml
  .github/actions/windows/build-artifacts/action.yml
  .github/actions/windows/install-dependencies/action.yml
  .github/actions/windows/release/action.yml
  .github/docker/Dockerfile
  .github/workflows/assets.yml
  .github/workflows/build-release-linux-amd64.yml
  .github/workflows/build-release-linux-arm64.yml
  .github/workflows/build-release-macos-amd64.yml
  .github/workflows/build-release-macos-arm64.yml
  .github/workflows/build-release-windows-amd64.yml
  .github/workflows/ci.yml
  .github/workflows/linting.yml
  .github/workflows/localizations.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  Dockerfile
  pubspec.yaml
Labels: feature

#157 feat(dashboard): implement navigation pane for dashboard screen
  CHANGELOG.md
  assets/icons/ic_about_us.svg
  assets/icons/ic_dashboard.svg
  assets/icons/ic_faqs.svg
  assets/icons/ic_node_logs.svg
  assets/icons/ic_settings.svg
  assets/icons/ic_transaction.svg
  assets/icons/ic_wallet.svg
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/src/core/common/navigation_pans/create_local_node_pane.dart
  lib/src/core/common/navigation_pans/remote_node_pane.dart
  lib/src/core/common/navigation_pans/restoring_node_pane.dart
  lib/src/core/utils/gen/assets/assets.gen.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/data/models/fluent_navigation_state_model.dart
  lib/src/data/models/fluent_navigation_state_model.freezed.dart
  lib/src/features/confirmation_seed/presentation/screen/confirmation_seed_screen.dart
  lib/src/features/dashboard/presentation/screen/dashboard_screen.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/initializing/presentation/screen/initializing_screen.dart
  lib/src/features/main/navigation_pan_cubit/presentation/cubits/navigation_pan_cubit.dart
  lib/src/features/master_password/presentation/screen/master_password_screen.dart
  lib/src/features/restoration_seed/presentation/screen/restoration_seed_screen.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  pubspec.yaml
Labels: feature
