Repository pactus-project/pactus-gui, pull requests merged in 2025-02, with the labels that each got.

#71 feat: impl `InitializingNavigationPane` for handling pactus initializing panel
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/src/core/common/colors/app_colors.dart
  lib/src/core/common/navigation_pans/dashboard_navigation_pane.dart
  lib/src/core/common/navigation_pans/initializing_navigation_pane.dart
  lib/src/core/common/widgets/custom_expandable_widget.dart
  lib/src/core/common/widgets/custom_filled_button.dart
  lib/src/core/common/widgets/custom_input_widget.dart
  lib/src/core/common/widgets/custom_password_widget.dart
  lib/src/core/common/widgets/custom_radio_button.dart
  lib/src/core/router/registration_routes.dart
  lib/src/core/router/route_name.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/confirmation_seed/presentation/screen/confirmation_seed_page.dart
  lib/src/features/finish/presentation/screen/finish_page.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/initialize_mode/presentation/sections/remote_node_section.dart
  lib/src/features/initialize_mode/presentation/widgets/auth_method_component.dart
  lib/src/features/initialize_mode/presentation/widgets/password_component.dart
  lib/src/features/initialize_mode/presentation/widgets/radio_button_group_widget.dart
  lib/src/features/initialize_mode/presentation/widgets/remote_address_component.dart
  lib/src/features/initialize_mode/presentation/widgets/username_component.dart
  lib/src/features/initializing/presentation/screen/initializing_page.dart
  lib/src/features/main/navigation_pan_cubit/presentation/cubits/navigation_pan_cubit.dart
  lib/src/features/main/radio_button_cubit/presentation/radio_button_cubit.dart
  lib/src/features/master_password/presentation/screen/master_password_page.dart
  lib/src/features/restoration_seed/presentation/screen/restoration_seed_page.dart
  lib/src/features/validator_config/presentation/screen/validator_config_page.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  pubspec.yaml
  test/src/core/common/widgets/theme_switcher_test.dart
Labels: enhancement

#87 feat: impl three different navigation pane for the three main flows of app
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/src/core/common/navigation_pans/create_local_node_pane.dart
  lib/src/core/common/navigation_pans/remote_node_pane.dart
  lib/src/core/common/navigation_pans/restoring_node_pane.dart
  lib/src/core/extensions/context_extensions.dart
  lib/src/core/router/registration_routes.dart
  lib/src/core/router/route_name.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_page.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  pubspec.yaml
  test/src/core/common/widgets/theme_switcher_test.dart
Labels: refactor

#79 Feat/implement wallet seed generation
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/src/core/common/colors/app_colors.dart
  lib/src/core/common/navigation_pans/initializing_navigation_pane.dart
  lib/src/core/common/widgets/adaptive_text_button.dart
  lib/src/core/common/widgets/custom_expandable_widget.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/generation_seed/core/constants/enums/seed_type_enum.dart
  lib/src/features/generation_seed/presentation/cubits/seed_type_cubit.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/generation_seed/presentation/sections/generation_seed_title_section.dart
  lib/src/features/generation_seed/presentation/sections/seed_notes_section.dart
  lib/src/features/generation_seed/presentation/sections/seeds_words_grid_section.dart
  lib/src/features/generation_seed/presentation/widgets/copy_to_clip_board_button.dart
  lib/src/features/generation_seed/presentation/widgets/seed_type_selector_widget.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/initialize_mode/presentation/widgets/auth_method_component.dart
  lib/src/features/initialize_mode/presentation/widgets/custom_input_row.dart
  lib/src/features/password/presentation/screen/unblock_password_screen.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  pubspec.yaml
Labels: feature

#83 docs: update README.md file for Pactus GUI
  README.md
Labels: documentation

#82 Feat/wallet seed confirmation
  lib/src/core/common/navigation_pans/initializing_navigation_pane.dart
  lib/src/core/router/registration_routes.dart
  lib/src/core/utils/daemon_manager/node_config_data.dart
  lib/src/features/confirmation_seed/data/models/seed_item_data.dart
  lib/src/features/confirmation_seed/presentation/bloc/confirmation_seed_cubit.dart
  lib/src/features/confirmation_seed/presentation/screen/confirmation_seed_page.dart
  lib/src/features/finish/presentation/screen/finish_page.dart
  lib/src/features/restoration_seed/presentation/screen/restoration_seed_page.dart
  pubspec.yaml
  test/src/core/common/widgets/theme_switcher_test.dart
Labels: feature

#90 fix(features:splashScreen): handle missing `Node` during app launch
  CHANGELOG.md
  lib/src/core/router/registration_routes.dart
  lib/src/core/utils/daemon_manager/node_config_data.dart
  lib/src/core/utils/gen/assets/assets.gen.dart
  lib/src/features/confirmation_seed/data/models/seed_item_data.dart
  lib/src/features/confirmation_seed/presentation/bloc/confirmation_seed_cubit.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  pubspec.yaml
Labels: bug

#81 feat: implement validator config screen
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/src/core/common/cubits/expandable_states_cubit.dart
  lib/src/core/common/navigation_pans/create_local_node_pane.dart
  lib/src/core/common/navigation_pans/initializing_navigation_pane.dart
  lib/src/core/common/navigation_pans/restoring_node_pane.dart
  lib/src/core/common/sections/navigation_footer_section.dart
  lib/src/core/common/widgets/custom_expandable_widget.dart
  lib/src/core/common/widgets/custom_input_widget.dart
  lib/src/core/common/widgets/custom_outlined_button.dart
  lib/src/core/common/widgets/custom_password_widget.dart
  lib/src/core/constants/app_constants.dart
  lib/src/core/router/registration_routes.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/dashboard/presentation/screen/dashboard_page.dart
  lib/src/features/finish/presentation/screen/finish_page.dart
  lib/src/features/generation_seed/presentation/widgets/seed_type_selector_widget.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/initialize_mode/presentation/widgets/auth_method_component.dart
  lib/src/features/initialize_mode/presentation/widgets/custom_input_row.dart
  lib/src/features/initialize_mode/presentation/widgets/remote_address_component.dart
  lib/src/features/master_password/presentation/screen/master_password_page.dart
  lib/src/features/validator_config/core/utils/methods/is_not_empty_directory_method.dart
  lib/src/features/validator_config/core/utils/methods/show_fluent_alert_method.dart
  lib/src/features/validator_config/presentation/cubits/validator_qty_cubit.dart
  lib/src/features/validator_config/presentation/screen/validator_config_page.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  lib/src/features/validator_config/presentation/sections/validator_config_title_section.dart
  lib/src/features/validator_config/presentation/sections/validator_qty_selector_section.dart
  pubspec.yaml
Labels: feature

#93 feat: implementation ui and logic of `FinishScreen`
  .github/workflows/ci.yml
  CHANGELOG.md
  assets/images/bg_finish_dark.svg
  assets/images/bg_finish_light.svg
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/src/core/common/navigation_pans/create_local_node_pane.dart
  lib/src/core/common/navigation_pans/initializing_navigation_pane.dart
  lib/src/core/common/navigation_pans/remote_node_pane.dart
  lib/src/core/common/navigation_pans/restoring_node_pane.dart
  lib/src/core/common/widgets/custom_filled_button.dart
  lib/src/core/common/widgets/custom_password_widget.dart
  lib/src/core/extensions/context_extensions.dart
  lib/src/core/router/app_router.dart
  lib/src/core/router/basic_routes.dart
  lib/src/core/router/registration_routes.dart
  lib/src/core/router/route_name.dart
  lib/src/core/utils/gen/assets/assets.gen.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/core/utils/storage_utils.dart
  lib/src/core/utils/string_extension.dart
  lib/src/features/confirmation_seed/presentation/screen/confirmation_seed_page.dart
  lib/src/features/finish/presentation/screen/finish_page.dart
  lib/src/features/initialize_mode/presentation/widgets/password_component.dart
  lib/src/features/password/presentation/screen/password_page.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  lib/src/features/welcome/presentation/screen/welcome_screen.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
Labels: feature

#95 feature/initializing page
  CHANGELOG.md
  assets/images/background_initializing.svg
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/src/core/common/cubits/expandable_states_cubit.dart
  lib/src/core/common/navigation_pans/create_local_node_pane.dart
  lib/src/core/common/navigation_pans/initializing_navigation_pane.dart
  lib/src/core/common/navigation_pans/remote_node_pane.dart
  lib/src/core/common/navigation_pans/restoring_node_pane.dart
  lib/src/core/common/widgets/custom_expandable_widget.dart
  lib/src/core/enums/app_enums.dart
  lib/src/core/router/registration_routes.dart
  lib/src/core/utils/daemon_manager/bloc/cli_command.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_cubit.dart
  lib/src/core/utils/gen/assets/assets.gen.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/generation_seed/core/constants/enums/seed_type_enum.dart
  lib/src/features/generation_seed/presentation/cubits/seed_type_cubit.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/generation_seed/presentation/widgets/seed_type_selector_widget.dart
  lib/src/features/initialize_mode/presentation/widgets/auth_method_component.dart
  lib/src/features/initializing/presentation/screen/initializing_page.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  lib/src/features/validator_config/presentation/cubits/validator_qty_cubit.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  lib/src/features/validator_config/presentation/sections/validator_qty_selector_section.dart
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
  pubspec.yaml
Labels: feature

#98 refactor: update bottom navigation and create base layout
  CHANGELOG.md
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/src/core/common/sections/navigation_footer_section.dart
  lib/src/core/common/widgets/custom_outlined_button.dart
  lib/src/core/common/widgets/standard_page_layout.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_cubit.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/features/confirmation_seed/presentation/screen/confirmation_seed_page.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/initializing/presentation/screen/initializing_page.dart
  lib/src/features/master_password/presentation/screen/master_password_page.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  lib/src/features/validator_config/presentation/sections/validator_config_title_section.dart
  pubspec.yaml
Labels: feature

#102 feat: implement UI for remote connect server page
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/src/core/common/widgets/custom_input_widget.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_screen.dart
  lib/src/features/initialize_mode/presentation/sections/remote_node_section.dart
  lib/src/features/initialize_mode/presentation/widgets/auth_method_component.dart
  lib/src/features/initialize_mode/presentation/widgets/password_component.dart
  lib/src/features/initialize_mode/presentation/widgets/remote_address_component.dart
  lib/src/features/initialize_mode/presentation/widgets/username_component.dart
  lib/src/features/initializing/presentation/screen/initializing_page.dart
  lib/src/features/validator_config/core/utils/methods/show_fluent_alert_method.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  pubspec.yaml
Labels: feature

#112 feat: restore wallet from seed and handel some related validations
  CHANGELOG.md
  lib/src/core/common/navigation_pans/create_local_node_pane.dart
  lib/src/core/common/navigation_pans/initializing_navigation_pane.dart
  lib/src/core/common/navigation_pans/remote_node_pane.dart
  lib/src/core/common/navigation_pans/restoring_node_pane.dart
  lib/src/core/common/sections/navigation_footer_section.dart
  lib/src/core/enums/app_enums.dart
  lib/src/features/initializing/presentation/screen/initializing_page.dart
  lib/src/features/master_password/presentation/screen/master_password_screen.dart
  lib/src/features/restoration_seed/presentation/screen/restoration_seed_screen.dart
  pubspec.yaml
Labels: feature

#113 feat: splash screen logic for wallet and node initialization
  CHANGELOG.md
  lib/src/core/router/basic_routes.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_cubit.dart
  lib/src/features/password/presentation/screen/unblock_password_screen.dart
  pubspec.yaml
Labels: feature

#111 fix some issues & final test on GUI
  CHANGELOG.md
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/src/core/common/cubits/step_validation_cubit.dart
  lib/src/core/common/navigation_pans/create_local_node_pane.dart
  lib/src/core/common/navigation_pans/initializing_navigation_pane.dart
  lib/src/core/common/navigation_pans/remote_node_pane.dart
  lib/src/core/common/navigation_pans/restoring_node_pane.dart
  lib/src/core/common/sections/navigation_footer_section.dart
  lib/src/core/common/widgets/screen_header_widget.dart
  lib/src/core/constants/app_constants.dart
  lib/src/core/router/basic_routes.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/features/confirmation_seed/data/models/seed_item_data.dart
  lib/src/features/confirmation_seed/presentation/bloc/confirmation_seed_cubit.dart
  lib/src/features/confirmation_seed/presentation/screen/confirmation_seed_page.dart
  lib/src/features/confirmation_seed/presentation/screen/confirmation_seed_screen.dart
  lib/src/features/confirmation_seed/presentation/sections/confirmation_seed_words_grid_section.dart
  lib/src/features/dashboard/presentation/screen/dashboard_screen.dart
  lib/src/features/finish/presentation/screen/finish_screen.dart
  lib/src/features/generation_seed/presentation/screens/generation_seed_screen.dart
  lib/src/features/generation_seed/presentation/sections/seeds_words_grid_section.dart
  lib/src/features/initializing/presentation/screen/initializing_screen.dart
  lib/src/features/main/navigation_pan_cubit/presentation/cubits/navigation_pan_cubit.dart
  lib/src/features/master_password/presentation/screen/master_password_screen.dart
  lib/src/features/master_password/presentation/sections/master_password_section.dart
  lib/src/features/password/presentation/screen/password_page.dart
  lib/src/features/password/presentation/screen/unblock_password_screen.dart
  lib/src/features/password/presentation/screen/unlock_password_screen.dart
  lib/src/features/restoration_seed/presentation/cubits/restoration_seed_cubit.dart
  lib/src/features/restoration_seed/presentation/screen/restoration_seed_screen.dart
  lib/src/features/restoration_seed/presentation/sections/restoration_seed_words_grid_section.dart
  lib/src/features/validator_config/presentation/screen/validator_config_screen.dart
  pubspec.yaml
Labels: feature
