Repository pactus-project/pactus-gui, pull requests merged in 2025-01, with the labels that each got.

#50 feat: ci/cd Integration for Automated Release Builds and Notifications
  .github/workflows/release.yml
  CHANGELOG.md
  pubspec.yaml
Labels: feature

#56 feat: migrate fonts , themes , colors and text styles to `widgetbook`
  CHANGELOG.md
  assets/fonts/Inter-Black.ttf
  assets/fonts/Inter-Bold.ttf
  assets/fonts/Inter-ExtraBold.ttf
  assets/fonts/Inter-ExtraLight.ttf
  assets/fonts/Inter-Light.ttf
  assets/fonts/Inter-Medium.ttf
  assets/fonts/Inter-Regular.ttf
  assets/fonts/Inter-SemiBold.ttf
  assets/fonts/Inter-Thin.ttf
  lib/main.dart
  lib/src/core/common/widgets/theme_switcher.dart
  lib/src/core/constants/inter_text_styles.dart
  lib/src/core/enums/theme_modes.dart
  lib/src/features/main/theme/bloc/theme_bloc.dart
  lib/src/features/main/theme/bloc/theme_event.dart
  lib/src/features/main/theme/bloc/theme_state.dart
  lib/src/features/main/theme/presentation/widgets/theme_selector.dart
  lib/src/features/main/theme/theme_data/app_theme_data.dart
  lib/src/features/main/theme/theme_data/pallets/on_surface_pallet.dart
  lib/src/features/main/theme/theme_data/pallets/surface_pallet.dart
  lib/src/features/password/presentation/screen/password_page.dart
  lib/src/features/splash_screen/presentation/screen/home_page.dart
  pubspec.yaml
  test/src/core/common/widgets/theme_switcher_test.dart
  test/src/features/main/theme/bloc/theme_bloc_test.dart
Labels: enhancement

#60 refactor: use `l10n` for localization and centralize translation keys
  .github/workflows/ci.yml
  CHANGELOG.md
  build_runner.sh
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/presentation/bloc/language_bloc/language_bloc.dart
  lib/src/core/common/widgets/theme_switcher.dart
  lib/src/core/utils/assets/assets.gen.dart
  lib/src/core/utils/gen/localization/app_locales.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/codegen_loader.g.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/core/utils/gen/localization/locale_keys.g.dart
  lib/src/core/utils/gen/localization/translations_utils.dart
  lib/src/features/main/language/core/language_constants.dart
  lib/src/features/main/language/core/localization_extension.dart
  lib/src/features/main/language/data/language_case.dart
  lib/src/features/main/language/presentation/bloc/language_bloc.dart
  lib/src/features/main/language/presentation/bloc/language_event.dart
  lib/src/features/main/language/presentation/bloc/language_state.dart
  lib/src/features/main/language/presentation/widget/language_widget.dart
  lib/src/features/main/theme/bloc/theme_bloc.dart
  lib/src/features/main/theme/bloc/theme_event.dart
  lib/src/features/main/theme/bloc/theme_state.dart
  lib/src/features/password/presentation/screen/password_page.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  lib/src/features/splash_screen/presentation/screen/home_page.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
  test/src/core/common/widgets/theme_switcher_test.dart
  test/src/features/main/language/presentation/bloc/language_bloc_test.dart
  test/src/features/main/theme/bloc/theme_bloc_test.dart
Labels: refactor

#66 Resolve Import Conflicts and Refactor Fluent UI Integration
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .metadata
  CHANGELOG.md
  devtools_options.yaml
  lib/main.dart
  lib/src/core/common/colors/app_colors.dart
  lib/src/core/common/widgets/theme_switcher.dart
  lib/src/core/common/widgets/toolbar_logo.dart
  lib/src/core/constants/configurations.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/features/confirmation_seed/presentation/screen/confirmation_seed_page.dart
  lib/src/features/dashboard/presentation/screen/dashboard_page.dart
  lib/src/features/finish/presentation/screen/finish_page.dart
  lib/src/features/initialize_mode/presentation/screen/initialize_mode_page.dart
  lib/src/features/initializing/presentation/screen/initializing_page.dart
  lib/src/features/main/language/core/localization_extension.dart
  lib/src/features/main/language/data/language_model.dart
  lib/src/features/main/language/presentation/widget/language_widget.dart
  lib/src/features/master_password/presentation/screen/master_password_page.dart
  lib/src/features/password/presentation/screen/password_page.dart
  lib/src/features/restoration_seed/presentation/screen/restoration_seed_page.dart
  lib/src/features/splash/presentation/screen/splash_screen.dart
  lib/src/features/splash_screen/presentation/screen/home_page.dart
  lib/src/features/validator_config/presentation/screen/validator_config_page.dart
  lib/src/features/welcome/presentation/screen/welcome_page.dart
  linux/CMakeLists.txt
  linux/runner/CMakeLists.txt
  linux/runner/main.cc
  linux/runner/my_application.cc
  linux/runner/my_application.h
  macos/Runner/AppDelegate.swift
  macos/Runner/Configs/AppInfo.xcconfig
  pubspec.yaml
  test/src/core/common/widgets/toolbar_logo_widget_test.dart
  web/index.html
  windows/runner/Runner.rc
Labels: bug

#67 Add functionality of initialize node in the background
  .gitignore
  CHANGELOG.md
  lib/src/core/router/registration_routes.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_cubit.dart
  lib/src/core/utils/daemon_manager/bloc/daemon_state.dart
  lib/src/core/utils/daemon_manager/node_config_data.dart
  lib/src/core/utils/daemon_manager/seed_generator.dart
  lib/src/features/finish/presentation/screen/finish_page.dart
  lib/src/features/master_password/presentation/screen/master_password_page.dart
  lib/src/features/restoration_seed/presentation/screen/restoration_seed_page.dart
  lib/src/features/validator_config/presentation/screen/validator_config_page.dart
  lib/src/features/welcome/presentation/screen/welcome_page.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugin_registrant.h
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature
